development:
   key:    "3136866110"
   secret: "b645824b7cffd216f97845dcff84f286"
   url:    "http://192.168.75.131:3000/"
   callback: "http://192.168.75.131:3000/syncs/sina/callback"
   add_blog_url: "http://api.t.sina.com.cn/statuses/upload.json"


production:
   key:    "3136866110"
   secret: "b645824b7cffd216f97845dcff84f286"
   url:    "http://chixinbugai.com"
   callback: "http://chixinbugai.com/syncs/sina/callback"
   add_blog_url: "http://api.t.sina.com.cn/statuses/upload.json"