development:
   key:    "3376020978"
   secret: "3ad4cff41b46346409de66e5e5c37741"
   url:    "http://localhost:3000"
   callback: "http://localhost:3000/syncs/sina/callback"
   add_blog_url: "http://api.t.sina.com.cn/statuses/update.json"
   add_blog_url2: "https://api.weibo.com/2/statuses/upload_url_text.json"
   user_info_url: ""


production:
   key:    "3376020978"
   secret: "3ad4cff41b46346409de66e5e5c37741"
   url:    "http://www.yinkuaizi.com"
   callback: "http://www.yinkuaizi.com/syncs/sina/callback"