development:
   key:    "12530659"
   secret: "9bf06028c06b37b4f643885700f6d1c6"
   url:    "http://chixinbugai.com"
   callback: "http://chixinbugai.com/syncs/taobao/callback"

production:
   key:    "12530659"
   secret: "9bf06028c06b37b4f643885700f6d1c6"
   url:    "http://chixinbugai.com"
   callback: "http://chixinbugai.com/syncs/taobao/callback"