module GlobalConstants
  # also notice the call to 'freeze'
  #default
  ITEMS_PER_PAGE_FEW = 5
  ITEMS_PER_PAGE_MANY = 20
  ITEMS_PER_PAGE_POPULAR = 10
  ITEMS_PER_PAGE_RECENT = 10
  ITEMS_PER_PAGE_HOT = 10
  ITEMS_PER_PAGE_GROUP = 10
  ITEMS_EFFECTIVE_DAYS = 14
  TAG_CLOUD_COUNT = 50
  CACHED_HOT_TAGS = 50
  MAX_TAGS = 5
  HOT_ARTICLES_ON_HOME_PAGE = 8
  NORMAL_USER_ROLE = 1
  AUTHORIZED_USER_ROLE = 3
  EDITOR_ROLE = 7
  ADMIN_ROLE = 9
  NORMAL_USER_VOTE_WEIGHT = 1
  EDITOR_VOTE_WEIGHT = 3
  ADMIN_VOTE_WEIGHT = 5
  VENDOR_RECENT_REVIEWS = 3
  TIME_FORMAT = '%m/%d/%Y'
  ITEM_MEASURE_RECENT_DAYS = 3
  ITEM_MEASURE_POPULAR = 20
  PROFILE_MIN_WATCHED_DISTANCE = 1
  PROFILE_MAX_WATCHED_DISTANCE = 5
  PROFILE_RECENT_ITEMS = 3
  COMMENTS_INTERVAL = 3
  GLOBAL_INPUT_MAX_LENGTH = 10000
  MAX_TAG_CHARS = 10
end
