module GlobalConstants
  # also notice the call to 'freeze'
  #default
  ITEMS_PER_PAGE_FEW = 5
  ITEMS_PER_PAGE_MANY = 20
  ITEMS_PER_PAGE_POPULAR = 10
  ITEMS_PER_PAGE_RECENT = 10
  ITEMS_PER_PAGE_HOT = 10
  ITEMS_PER_PAGE_GROUP = 10
  ITEMS_EFFECTIVE_DAYS = 14
  TAG_CLOUD_COUNT = 5
  CACHED_HOT_TAGS = 30
  MAX_TAGS = 5
  HOT_ARTICLES_ON_HOME_PAGE = 10
  NORMAL_USER_ROLE = 1
  AUTHORIZED_USER_ROLE = 3
  EDITOR_ROLE = 7
  ADMIN_ROLE = 9
  VENDOR_RECENT_REVIEWS = 3
  TIME_FORMAT = '%m/%d/%Y'
  ITEM_MEASURE_RECENT_DAYS = 3
  ITEM_MEASURE_POPULAR = 20
end
