和乐康:
  #skipped: true
  entries:
    ["http://www.helekang.com/"]
  elements:
    listed_first_catalog: '#cat_product h1'
    listed_second_catalog: '.on li'
    listed_product: 'div.list_item'
    product_name: '#goods_info h1'
    product_image: '#img img.p_img'
    product_price: '#info .price'
    next_link_text: '下一页'