京东商城:
  skipped: true
  entries:
    ["http://search.360buy.com/Search?keyword=%D3%D0%BB%FA%CA%B3%C6%B7",
    "http://search.360buy.com/Search?keyword=%C2%CC%C9%AB%CA%B3%C6%B7"]
  elements:
    listed_product: '#plist li'
    product_name: '#name h1'
    next_link: 'a.next'


1号店:
  skipped: true
  entries:
    ["http://search.yihaodian.com/s/c0-k%25E6%259C%2589%25E6%259C%25BA%25E9%25A3%259F%25E5%2593%2581",
    "http://search.yihaodian.com/s/c0-k%25E7%25BB%25BF%25E8%2589%25B2%25E9%25A3%259F%25E5%2593%2581"]
  elements:
    listed_product: '#productcontent .producteg.fl'
    product_name: '#productMainName'
    next_link: '.latestnewnextpage a'


五谷磨房:
  skipped: false
  entries:
    ["http://www.iwugu.com/?gallery-57-grid.html",
    "http://www.iwugu.com/?gallery-64-grid.html",
    "http://www.iwugu.com/?gallery-80-grid.html",
    "http://www.iwugu.com/?gallery-71-grid.html",
    "http://www.iwugu.com/?gallery-117-grid.html"]
  elements:
    listed_product: 'div.items-gallery'
    product_name: 'h1.goodsname'
    product_image: "div.goods-detail-pic img"
    next_link: 'a.next'
