京东商城:
  skipped: true
  entries:
    ["http://search.360buy.com/Search?keyword=%D3%D0%BB%FA%CA%B3%C6%B7",
    "http://search.360buy.com/Search?keyword=%C2%CC%C9%AB%CA%B3%C6%B7"]
  elements:
    listed_product: '#plist li'
    product_name: '#name h1'
    product_image: "#preview #spec-n1 img"
#    product_price: '.price'
    next_link: 'a.next'


1号店:
  skipped: true
  entries:
    ["http://search.yihaodian.com/s/c0-k%25E6%259C%2589%25E6%259C%25BA%25E9%25A3%259F%25E5%2593%2581",
    "http://search.yihaodian.com/s/c0-k%25E7%25BB%25BF%25E8%2589%25B2%25E9%25A3%259F%25E5%2593%2581"]
  elements:
    listed_product: '#productcontent .producteg.fl'
    product_name: '#productMainName'
    product_image: "#productImg"
    product_price: '.productPriceSpan'
    product_weight: '#format'
    next_link_css_selector: '.latestnewnextpage a'
  comment_selectors:
    skip_comments: false
    listed_comment: ".evalist"
    comment_text: ".middleli div"
    next_commnet_css_selector: ".latestnewnextpage a"

五谷磨房:
  skipped: true
  entries:
    ["http://www.iwugu.com/?gallery-57-grid.html",
    "http://www.iwugu.com/?gallery-64-grid.html",
    "http://www.iwugu.com/?gallery-80-grid.html",
    "http://www.iwugu.com/?gallery-71-grid.html",
    "http://www.iwugu.com/?gallery-117-grid.html"]
  elements:
    listed_product: 'div.items-gallery'
    product_name: 'h1.goodsname'
    product_image: "div.goods-detail-pic img"
    product_price: '.goods-price .price1'
    product_weight: '#goodsWeight'
    next_link_css_selector: 'a.next'

和乐康:
  skipped: true
  entries:
    ["http://www.helekang.com/category-12-m-b-c-k-min-max-extcode-----ShuCai.html",
    "http://www.helekang.com/category-104-m-b-c-k-min-max-extcode-----ShuiGuoHOT!.html",
    "http://www.helekang.com/category-26-m-b-c-k-min-max-extcode-----RouQinDanNaiDouZhiPin.html",
    "http://www.helekang.com/category-77-m-b-c-k-min-max-extcode-----JinKouShiPin.html",
    "http://www.helekang.com/category-226-m-b-c-k-min-max-extcode-----ShuiChanHaiXian.html"]
  elements:
    listed_product: 'div.list_item'
    product_name: '#goods_info h1'
    product_image: '#img img.p_img'
    product_price: '#info .price'
    next_link_text: '下一页'

